
package com.saviasaludeps.recuperar.wsdl.adjuntos;

import com.saviasaludeps.recuperar.generico.PropApl;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultarAnexoRadOrigenService", targetNamespace = "http://www.servisoft.com.co/Mercurio/Servicios/Contract/ConsultarAnexoRadOrigen", wsdlLocation = "http://190.60.28.47:7070/mercurio/ConsultarAnexoRadOrigenService?wsdl")
public class ConsultarAnexoRadOrigenService
    extends Service
{

    private final static URL CONSULTARANEXORADORIGENSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTARANEXORADORIGENSERVICE_EXCEPTION;
    private final static QName CONSULTARANEXORADORIGENSERVICE_QNAME = new QName("http://www.servisoft.com.co/Mercurio/Servicios/Contract/ConsultarAnexoRadOrigen", "ConsultarAnexoRadOrigenService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(PropApl.getInstance().get(PropApl.URL_WS_SOAP_ADJUNTOS));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTARANEXORADORIGENSERVICE_WSDL_LOCATION = url;
        CONSULTARANEXORADORIGENSERVICE_EXCEPTION = e;
    }

    public ConsultarAnexoRadOrigenService() {
        super(__getWsdlLocation(), CONSULTARANEXORADORIGENSERVICE_QNAME);
    }

    public ConsultarAnexoRadOrigenService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTARANEXORADORIGENSERVICE_QNAME, features);
    }

    public ConsultarAnexoRadOrigenService(URL wsdlLocation) {
        super(wsdlLocation, CONSULTARANEXORADORIGENSERVICE_QNAME);
    }

    public ConsultarAnexoRadOrigenService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTARANEXORADORIGENSERVICE_QNAME, features);
    }

    public ConsultarAnexoRadOrigenService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarAnexoRadOrigenService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultarAnexoRadOrigenInterface
     */
    @WebEndpoint(name = "ConsultarAnexoRadOrigenSOAP")
    public ConsultarAnexoRadOrigenInterface getConsultarAnexoRadOrigenSOAP() {
        return super.getPort(new QName("http://www.servisoft.com.co/Mercurio/Servicios/Contract/ConsultarAnexoRadOrigen", "ConsultarAnexoRadOrigenSOAP"), ConsultarAnexoRadOrigenInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarAnexoRadOrigenInterface
     */
    @WebEndpoint(name = "ConsultarAnexoRadOrigenSOAP")
    public ConsultarAnexoRadOrigenInterface getConsultarAnexoRadOrigenSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.servisoft.com.co/Mercurio/Servicios/Contract/ConsultarAnexoRadOrigen", "ConsultarAnexoRadOrigenSOAP"), ConsultarAnexoRadOrigenInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTARANEXORADORIGENSERVICE_EXCEPTION!= null) {
            throw CONSULTARANEXORADORIGENSERVICE_EXCEPTION;
        }
        return CONSULTARANEXORADORIGENSERVICE_WSDL_LOCATION;
    }

}
