
package com.saviasaludeps.recuperar.wsdl.adjuntos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultarAnexoRadOrigenInterface", targetNamespace = "http://www.servisoft.com.co/Mercurio/Servicios/Contract/ConsultarAnexoRadOrigen")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultarAnexoRadOrigenInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.saviasaludeps.recuperar.wsdl.adjuntos.AnexoRadicadoResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarAnexoRadicado", targetNamespace = "http://www.servisoft.com.co/Mercurio/Servicios/Contract/ConsultarAnexoRadOrigen", className = "com.saviasaludeps.recuperar.wsdl.adjuntos.ConsultarAnexoRadicado")
    @ResponseWrapper(localName = "consultarAnexoRadicadoResponse", targetNamespace = "http://www.servisoft.com.co/Mercurio/Servicios/Contract/ConsultarAnexoRadOrigen", className = "com.saviasaludeps.recuperar.wsdl.adjuntos.ConsultarAnexoRadicadoResponse")
    public AnexoRadicadoResponse consultarAnexoRadicado(
        @WebParam(name = "arg0", targetNamespace = "")
        AnexoRadicadoRequest arg0);

}
