
package com.saviasaludeps.recuperar.wsdl.anexos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultarAnexosRelacionadosInterface", targetNamespace = "http://www.servisoft.com.co/Mercurio/Servicios/Contract/ConsultarAnexosRelacionados")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultarAnexosRelacionadosInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.saviasaludeps.recuperar.wsdl.anexos.ConsultarAnexosRelacionadosResponseAlt
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarAnexosRelacionados", targetNamespace = "http://www.servisoft.com.co/Mercurio/Servicios/Contract/ConsultarAnexosRelacionados", className = "com.saviasaludeps.recuperar.wsdl.anexos.ConsultarAnexosRelacionados")
    @ResponseWrapper(localName = "consultarAnexosRelacionadosResponse", targetNamespace = "http://www.servisoft.com.co/Mercurio/Servicios/Contract/ConsultarAnexosRelacionados", className = "com.saviasaludeps.recuperar.wsdl.anexos.ConsultarAnexosRelacionadosResponse")
    public ConsultarAnexosRelacionadosResponseAlt consultarAnexosRelacionados(
        @WebParam(name = "arg0", targetNamespace = "")
        ConsultarAnexosRelacionadosRequest arg0);

}
