
package com.saviasaludeps.recuperar.wsdl.anexos;

import com.saviasaludeps.recuperar.generico.PropApl;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultarAnexosRelacionadosService", targetNamespace = "http://www.servisoft.com.co/Mercurio/Servicios/Contract/ConsultarAnexosRelacionados", wsdlLocation = "http://190.60.28.47:7070/mercurio/ConsultarAnexosRelacionadosService?wsdl")
public class ConsultarAnexosRelacionadosService
    extends Service
{

    private final static URL CONSULTARANEXOSRELACIONADOSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTARANEXOSRELACIONADOSSERVICE_EXCEPTION;
    private final static QName CONSULTARANEXOSRELACIONADOSSERVICE_QNAME = new QName("http://www.servisoft.com.co/Mercurio/Servicios/Contract/ConsultarAnexosRelacionados", "ConsultarAnexosRelacionadosService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(PropApl.getInstance().get(PropApl.URL_WS_SOAP_ANEXOS));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTARANEXOSRELACIONADOSSERVICE_WSDL_LOCATION = url;
        CONSULTARANEXOSRELACIONADOSSERVICE_EXCEPTION = e;
    }

    public ConsultarAnexosRelacionadosService() {
        super(__getWsdlLocation(), CONSULTARANEXOSRELACIONADOSSERVICE_QNAME);
    }

    public ConsultarAnexosRelacionadosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTARANEXOSRELACIONADOSSERVICE_QNAME, features);
    }

    public ConsultarAnexosRelacionadosService(URL wsdlLocation) {
        super(wsdlLocation, CONSULTARANEXOSRELACIONADOSSERVICE_QNAME);
    }

    public ConsultarAnexosRelacionadosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTARANEXOSRELACIONADOSSERVICE_QNAME, features);
    }

    public ConsultarAnexosRelacionadosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarAnexosRelacionadosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultarAnexosRelacionadosInterface
     */
    @WebEndpoint(name = "ConsultarAnexosRelacionadosSOAP")
    public ConsultarAnexosRelacionadosInterface getConsultarAnexosRelacionadosSOAP() {
        return super.getPort(new QName("http://www.servisoft.com.co/Mercurio/Servicios/Contract/ConsultarAnexosRelacionados", "ConsultarAnexosRelacionadosSOAP"), ConsultarAnexosRelacionadosInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarAnexosRelacionadosInterface
     */
    @WebEndpoint(name = "ConsultarAnexosRelacionadosSOAP")
    public ConsultarAnexosRelacionadosInterface getConsultarAnexosRelacionadosSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.servisoft.com.co/Mercurio/Servicios/Contract/ConsultarAnexosRelacionados", "ConsultarAnexosRelacionadosSOAP"), ConsultarAnexosRelacionadosInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTARANEXOSRELACIONADOSSERVICE_EXCEPTION!= null) {
            throw CONSULTARANEXOSRELACIONADOSSERVICE_EXCEPTION;
        }
        return CONSULTARANEXOSRELACIONADOSSERVICE_WSDL_LOCATION;
    }

}
